# Generated by Django 4.0.4 on 2022-05-09 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_pessoa_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='data_criacao',
            new_name='data_de_nascimento',
        ),
    ]
